/* ═══════════════════════════════════════════════
   data.js — Module definitions + activity data
   All 16 IAM missions for NEXUS Corp.
   ═══════════════════════════════════════════════ */

const LEVELS = [
  { min: 0,     label: 'IAM Intern',      next: 500   },
  { min: 500,   label: 'IAM Analyst',     next: 1500  },
  { min: 1500,  label: 'IAM Engineer',    next: 3000  },
  { min: 3000,  label: 'IAM Architect',   next: 5500  },
  { min: 5500,  label: 'IAM Director',    next: 9000  },
  { min: 9000,  label: 'CISO',            next: 14000 },
  { min: 14000, label: 'Identity Master', next: 99999 },
];

const ACHIEVEMENTS = [
  { id: 'first_blood',   icon: '🎯', name: 'First Mission',      desc: 'Complete your first mission.' },
  { id: 'mfa_evangelist',icon: '🔐', name: 'MFA Evangelist',     desc: 'Complete Mission 02 with 3 stars.' },
  { id: 'policy_wonk',   icon: '📋', name: 'Policy Wonk',        desc: 'Complete Mission 03.' },
  { id: 'chain_of_trust',icon: '🔗', name: 'Chain of Trust',     desc: 'Complete Mission 12 (PKI).' },
  { id: 'zero_trust',    icon: '🛡️', name: 'Zero Trust Zealot',  desc: 'Complete Mission 15 with 3 stars.' },
  { id: 'all_missions',  icon: '🏆', name: 'Identity Master',    desc: 'Complete all 16 missions.' },
  { id: 'speed_demon',   icon: '⚡', name: 'Speed Demon',        desc: 'Earn 3 stars on any mission.' },
  { id: 'jml_master',    icon: '🔄', name: 'JML Master',         desc: 'Complete Mission 06 (Provisioning).' },
  { id: 'fed_builder',   icon: '🌐', name: 'Federation Builder', desc: 'Complete Mission 07 (Federation).' },
  { id: 'token_router',  icon: '🎫', name: 'Token Router',       desc: 'Complete Mission 08 (OAuth/OIDC).' },
  { id: 'privacy_guard', icon: '🔒', name: 'Privacy Guardian',   desc: 'Complete Mission 10 (Privacy).' },
  { id: 'machine_whisperer', icon: '🤖', name: 'Machine Whisperer', desc: 'Complete Mission 13 (Non-Human).' },
  { id: 'least_priv',    icon: '✂️', name: 'Permission Pruner',  desc: 'Complete Mission 15 (Least Privilege).' },
  { id: 'future_id',     icon: '🌟', name: 'DID Pioneer',        desc: 'Complete Mission 16 (Decentralized).' },
  { id: 'perfect_run',   icon: '💎', name: 'Diamond Run',        desc: 'Get 3 stars on 5 missions in a row.' },
];

/* ─────────────────────────────────────────────
   MODULES — each has: id, mission, icon, color,
   title, subtitle, context, bullets, activities[]
   ───────────────────────────────────────────── */
const MODULES = [

  /* ── M01: Identity Fundamentals ─────────── */
  {
    id: 1, mission: 'M01', icon: '🆔', color: '#00d4ff',
    title: 'Who Are You?',
    subtitle: 'Identity Fundamentals',
    context: 'Day 1 at NEXUS Corp. 500 employees share accounts, use personal emails for work systems, and have no consistent naming. Your first mission: establish what a digital identity actually is.',
    bullets: [
      'A digital identity has three parts: Identifiers, Attributes, and Credentials',
      'Identifiers are unique, stable system references (not usernames)',
      'Every identity follows a lifecycle: Joiner → Mover → Leaver',
      'Identity Assurance Levels define how confident you are someone is who they claim',
    ],
    activities: [
      {
        type: 'sort', id: 'm01-sort1',
        title: 'Build the Identity Record',
        instruction: 'Every employee record contains different kinds of data. Click each item to place it in the correct category — Identifiers (unique system refs), Attributes (descriptive info), or Credentials (proof of identity).',
        bins: [
          { id: 'identifier', label: 'Identifier',  icon: '🔑', desc: 'Unique, stable system reference', color: '#00d4ff' },
          { id: 'attribute',  label: 'Attribute',   icon: '📋', desc: 'Descriptive data about the person', color: '#7c3aed' },
          { id: 'credential', label: 'Credential',  icon: '🛡️', desc: 'Used to prove who you are', color: '#f59e0b' },
        ],
        items: [
          { text: 'Employee ID: EMP-10042', bin: 'identifier', explain: 'A unique, stable system reference. It never changes even if the person\'s name or role changes.' },
          { text: 'Department: Engineering', bin: 'attribute', explain: 'An attribute — descriptive data that tells you something about who this person is.' },
          { text: 'Password (hashed)', bin: 'credential', explain: 'A credential — something you know, used to prove your identity during authentication.' },
          { text: 'Job Title: Senior Developer', bin: 'attribute', explain: 'An attribute. Job titles describe a person\'s role and often drive access decisions in RBAC.' },
          { text: 'UUID: a3f7-b829', bin: 'identifier', explain: 'A globally unique identifier generated by the system — the definitive reference for this identity.' },
          { text: 'Fingerprint Template', bin: 'credential', explain: 'A biometric credential — something you ARE. Used in "something you are" authentication.' },
          { text: 'Location: Austin, TX', bin: 'attribute', explain: 'An attribute. Location data can be used in ABAC policies to control access based on geography.' },
          { text: 'Hardware Token Serial', bin: 'credential', explain: 'A physical credential — something you HAVE. This is the second factor in MFA setups.' },
        ],
      },
      {
        type: 'configure', id: 'm01-cfg1',
        title: 'The Username vs Identifier Crisis',
        instruction: 'NEXUS has 3 employees named "John Smith" — all chose "johnsmith" as their username. Configure the identity system to fix this. Watch how each change affects system health.',
        scenarios: [
          {
            icon: '😱', name: 'The Three Smiths Problem',
            context: 'Three John Smiths. One username. Payroll is sending checks to the wrong person. The IT helpdesk is overwhelmed.',
            details: 'Risk: HIGH — System cannot distinguish between identities. Payroll errors, wrong access granted.',
          },
        ],
        toggles: [
          { id: 'unique_id',   label: 'Assign unique Employee IDs', sub: 'Separate from display name',   impact: { security: 40, clarity: 50, risk: -60 } },
          { id: 'sep_ids',     label: 'Separate identifiers from usernames', sub: 'Usernames = human; IDs = system', impact: { security: 30, clarity: 40, risk: -30 } },
          { id: 'email_login', label: 'Use company email as login alias', sub: 'Still backed by unique ID',  impact: { security: 10, clarity: 20, risk: -10 } },
        ],
        targetToggles: ['unique_id', 'sep_ids'],
        successMessage: 'With unique Employee IDs separated from human-readable usernames, the system can always distinguish identities — even when names are identical. Identifiers must be unique, stable, and system-controlled.',
      },
      {
        type: 'sort', id: 'm01-sort2',
        title: 'Lifecycle Events at NEXUS',
        instruction: 'Events happen every day at NEXUS Corp. Sort each event into the correct phase of the Joiner / Mover / Leaver identity lifecycle.',
        bins: [
          { id: 'joiner', label: 'Joiner',  icon: '🟢', desc: 'New identity needs creation', color: '#10b981' },
          { id: 'mover',  label: 'Mover',   icon: '🔵', desc: 'Existing identity needs updating', color: '#00d4ff' },
          { id: 'leaver', label: 'Leaver',  icon: '🔴', desc: 'Identity access must be removed', color: '#ef4444' },
        ],
        items: [
          { text: 'Emma starts as a new Sales Rep today', bin: 'joiner', explain: 'A Joiner event. Emma\'s identity needs to be created and initial birthright access provisioned.' },
          { text: 'Marcus moves from Engineering to Product Management', bin: 'mover', explain: 'A Mover event. Marcus\'s existing identity needs access updated — old engineering access removed, PM access granted.' },
          { text: 'Priya retires after 12 years at NEXUS', bin: 'leaver', explain: 'A Leaver event. All of Priya\'s access must be revoked and her account disabled or deleted.' },
          { text: 'A contractor joins for a 6-month project', bin: 'joiner', explain: 'Still a Joiner — any new identity entering the system requires creation and provisioning, even contractors.' },
          { text: 'Dev gets promoted to Engineering Lead', bin: 'mover', explain: 'A Mover event. Promotion means role change — access must be updated to reflect the new responsibilities.' },
          { text: 'Carol\'s contract ends after 3 months', bin: 'leaver', explain: 'A Leaver event. When someone exits — even a contractor — all access must be immediately revoked.' },
        ],
      },
    ],
    concepts: ['Identifiers vs Usernames vs Attributes vs Credentials', 'Joiner / Mover / Leaver lifecycle', 'Why stable unique identifiers matter'],
    xpReward: 300,
    achievementUnlock: 'first_blood',
  },

  /* ── M02: Authentication & Authorization ─── */
  {
    id: 2, mission: 'M02', icon: '🔐', color: '#7c3aed',
    title: 'Prove It',
    subtitle: 'Authentication & Authorization',
    context: 'NEXUS was breached last week. An attacker guessed a VP\'s password and accessed the financial system. The board wants answers. Your mission: redesign authentication across the entire company.',
    bullets: [
      'Authentication (AuthN) proves WHO you are; Authorization (AuthZ) controls WHAT you can do',
      'Three auth factors: Something you Know, Have, or Are',
      'MFA combines 2+ factors — a stolen password alone isn\'t enough',
      'Adaptive auth adjusts requirements based on risk signals (time, location, behavior)',
    ],
    activities: [
      {
        type: 'sort', id: 'm02-sort1',
        title: 'The Three Factors',
        instruction: 'Authentication factors fall into three categories. Sort each method into the correct category.',
        bins: [
          { id: 'know', label: 'Something You Know', icon: '🧠', desc: 'Memory-based secret', color: '#00d4ff' },
          { id: 'have', label: 'Something You Have', icon: '📱', desc: 'Physical token or device', color: '#7c3aed' },
          { id: 'are',  label: 'Something You Are',  icon: '👁️', desc: 'Biometric characteristic', color: '#10b981' },
        ],
        items: [
          { text: 'Password', bin: 'know', explain: 'A classic "something you know" factor. Alone it\'s the weakest — it can be stolen, guessed, or phished.' },
          { text: 'SMS One-Time Code', bin: 'have', explain: 'Something you have — your phone receives the code. Better than password alone, but SMS can be SIM-swapped.' },
          { text: 'Fingerprint scan', bin: 'are', explain: 'A biometric — something you ARE. Can\'t be forgotten, but can\'t be changed if compromised.' },
          { text: 'Security PIN', bin: 'know', explain: 'Still something you know. Short PINs are weak; they should be combined with another factor.' },
          { text: 'Hardware security key (YubiKey)', bin: 'have', explain: 'The gold standard of "something you have" — phishing-resistant and tied to specific origins.' },
          { text: 'Face recognition', bin: 'are', explain: 'Biometric — something you are. Convenient but raises privacy concerns in some jurisdictions.' },
          { text: 'Authenticator app TOTP', bin: 'have', explain: 'The app lives on your device — something you have. TOTP codes rotate every 30 seconds.' },
          { text: 'Passphrase (long password)', bin: 'know', explain: 'Still knowledge-based. Longer is better, but it\'s still just one factor without a second.' },
        ],
      },
      {
        type: 'configure', id: 'm02-cfg1',
        title: 'Adaptive Authentication Design',
        instruction: 'Configure authentication for each NEXUS scenario. Too weak = breach risk. Too strong = productivity loss. Find the right balance.',
        scenarios: [
          { icon: '🏢', name: 'Employee — Office Network, 9am', context: 'Known device, trusted IP, normal hours.', details: 'Risk level: LOW. User is on-site, trusted environment.' },
          { icon: '🌍', name: 'CFO — Logging In from Abroad at 2am', context: 'Unknown location, unusual hours, accessing payroll.', details: 'Risk level: CRITICAL. Multiple red flags. Payroll access at stake.' },
          { icon: '👤', name: 'Customer — Resetting Password', context: 'Self-service portal. Identity not verified.', details: 'Risk level: MEDIUM. Account takeover via password reset is common.' },
        ],
        toggles: [
          { id: 'password',     label: 'Password required',          sub: 'Basic first factor',            impact: { security: 20, ux: 70, risk: -20 } },
          { id: 'mfa_sms',      label: 'SMS MFA',                    sub: '+1 factor via mobile',          impact: { security: 30, ux: 50, risk: -25 } },
          { id: 'mfa_app',      label: 'Authenticator app required', sub: '+1 phishing-resistant factor',  impact: { security: 40, ux: 40, risk: -35 } },
          { id: 'hardware_key', label: 'Hardware key required',      sub: 'Strongest — phishing-proof',   impact: { security: 50, ux: 20, risk: -45 } },
          { id: 'geo_block',    label: 'Block unusual locations',    sub: 'Alert + step-up auth',          impact: { security: 30, ux: 30, risk: -30 } },
        ],
        targetToggles: ['password', 'mfa_app', 'geo_block'],
        successMessage: 'Adaptive authentication uses risk signals (location, time, device) to step up requirements when risk is high. A CFO logging in from abroad at 2am needs much stronger verification than an employee on the office network.',
      },
      {
        type: 'sort', id: 'm02-sort2',
        title: 'AuthN vs AuthZ',
        instruction: 'Authentication and authorization are different concepts. Sort each statement into the correct category.',
        bins: [
          { id: 'authn', label: 'Authentication (AuthN)', icon: '🪪', desc: 'Proves who you are', color: '#00d4ff' },
          { id: 'authz', label: 'Authorization (AuthZ)',  icon: '🚪', desc: 'Controls what you can do', color: '#7c3aed' },
        ],
        items: [
          { text: '"You are who you claim to be"', bin: 'authn', explain: 'Authentication establishes identity — it answers "who are you?"' },
          { text: '"You may read this file but not delete it"', bin: 'authz', explain: 'Authorization determines permissions — it answers "what can you do?"' },
          { text: 'Checking your password', bin: 'authn', explain: 'Password verification is an authentication step — it validates your claimed identity.' },
          { text: '"Only HR can view salary data"', bin: 'authz', explain: 'This is an access rule — authorization policy that controls who can do what.' },
          { text: 'MFA prompt when logging in', bin: 'authn', explain: 'MFA is an authentication mechanism — additional proof that you are who you claim.' },
          { text: 'Role-based access control policies', bin: 'authz', explain: 'RBAC policies define what authenticated users are allowed to do — that\'s authorization.' },
        ],
      },
    ],
    concepts: ['Authentication proves identity; Authorization grants permissions', 'Three factors: Know, Have, Are', 'Adaptive auth scales strength to risk level'],
    xpReward: 320,
    achievementUnlock: 'mfa_evangelist',
  },

  /* ── M03: Access Control ─────────────────── */
  {
    id: 3, mission: 'M03', icon: '🚪', color: '#10b981',
    title: 'Access Denied',
    subtitle: 'Access Control Models',
    context: 'NEXUS just failed an audit. Engineers have admin access to HR data. Sales has access to source code. Everyone can read finance reports. You need to build a proper access control framework.',
    bullets: [
      'DAC: Resource owners control who gets access (flexible but risky)',
      'RBAC: Access is granted based on job role (simple and scalable)',
      'ABAC: Access is based on attributes of user, resource, and environment',
      'The PAP writes policies, PDP decides, PEP enforces, PIP provides attributes',
    ],
    activities: [
      {
        type: 'sort', id: 'm03-sort1',
        title: 'Access Control Models in the Wild',
        instruction: 'NEXUS is evaluating different access control approaches. Sort each scenario description into the model it best represents.',
        bins: [
          { id: 'dac',  label: 'DAC',  icon: '👤', desc: 'Owner controls access', color: '#f59e0b' },
          { id: 'rbac', label: 'RBAC', icon: '👥', desc: 'Role determines access', color: '#00d4ff' },
          { id: 'abac', label: 'ABAC', icon: '🏷️', desc: 'Attributes drive access', color: '#7c3aed' },
          { id: 'pbac', label: 'PBAC', icon: '📜', desc: 'Policy engine decides', color: '#10b981' },
        ],
        items: [
          { text: '"All Managers get read access to budget reports automatically"', bin: 'rbac', explain: 'RBAC: access is tied to the "Manager" role. When someone becomes a manager, they get the access automatically.' },
          { text: '"Alex created this document so Alex decides who else can read it"', bin: 'dac', explain: 'DAC: the owner (Alex) has discretion over who accesses their resource. Common in file systems.' },
          { text: '"Contractors in EU can access the system only during business hours on company devices"', bin: 'abac', explain: 'ABAC: combines user attribute (contractor, EU location), time attribute, and device attribute to make the decision.' },
          { text: '"Our central policy engine evaluates every access request against written rules before granting access"', bin: 'pbac', explain: 'PBAC: a dedicated policy engine processes all access decisions based on formal policy definitions.' },
          { text: '"When you become a Developer, you automatically get access to GitHub and the staging environment"', bin: 'rbac', explain: 'RBAC: developer role = defined set of permissions. Role assignment drives access provisioning.' },
          { text: '"Senior employees who are on-site can access the executive floor during weekdays"', bin: 'abac', explain: 'ABAC: multiple attributes (seniority, location, time) all factor into the access decision.' },
        ],
      },
      {
        type: 'flow', id: 'm03-flow1',
        title: 'The Policy Enforcement Flow',
        instruction: 'When Alex tries to access payroll data, a chain of components processes the request. Arrange the steps in the correct order to show how PBAC works.',
        correctOrder: [
          'Alex sends access request to the application',
          'Policy Enforcement Point (PEP) intercepts the request',
          'PEP asks the Policy Decision Point (PDP) for a decision',
          'PDP queries the Policy Information Point (PIP) for attributes',
          'PDP evaluates the request against policies from the Policy Administration Point (PAP)',
          'PDP returns PERMIT or DENY to the PEP',
          'PEP enforces the decision — grants or blocks access',
        ],
        steps: [
          'PEP asks the Policy Decision Point (PDP) for a decision',
          'PEP enforces the decision — grants or blocks access',
          'Alex sends access request to the application',
          'PDP queries the Policy Information Point (PIP) for attributes',
          'Policy Enforcement Point (PEP) intercepts the request',
          'PDP evaluates the request against policies from the Policy Administration Point (PAP)',
          'PDP returns PERMIT or DENY to the PEP',
        ],
        successMessage: 'The PAP stores policies. The PIP provides identity attributes. The PDP makes the access decision. The PEP enforces it. These four components are the foundation of policy-based authorization.',
      },
      {
        type: 'sort', id: 'm03-sort2',
        title: 'Who Does What? PAP / PDP / PEP / PIP',
        instruction: 'Sort each responsibility to the correct access control component.',
        bins: [
          { id: 'pap', label: 'PAP', icon: '📝', desc: 'Policy Administration Point', color: '#f59e0b' },
          { id: 'pdp', label: 'PDP', icon: '⚖️', desc: 'Policy Decision Point',       color: '#00d4ff' },
          { id: 'pep', label: 'PEP', icon: '🚧', desc: 'Policy Enforcement Point',    color: '#ef4444' },
          { id: 'pip', label: 'PIP', icon: '📊', desc: 'Policy Information Point',    color: '#10b981' },
        ],
        items: [
          { text: 'Sits in front of the resource and blocks or allows requests', bin: 'pep', explain: 'The PEP is the gatekeeper — it physically intercepts requests and enforces whatever the PDP decides.' },
          { text: 'Stores and manages the written access policies', bin: 'pap', explain: 'The PAP is where policies are authored and stored. Administrators write rules here.' },
          { text: 'Looks up user attributes like role, department, clearance level', bin: 'pip', explain: 'The PIP is the attribute store — it supplies context data (who is this person? what attributes do they have?) to the PDP.' },
          { text: 'Evaluates the request and returns a PERMIT or DENY decision', bin: 'pdp', explain: 'The PDP is the brain — it reads the policy, gets attributes from the PIP, and makes the actual access decision.' },
          { text: 'Retrieves real-time data like location, device health, risk score', bin: 'pip', explain: 'The PIP provides dynamic attributes too — not just static data, but real-time context for the decision.' },
          { text: 'Where security teams write "only Managers can approve expenses"', bin: 'pap', explain: 'Policy authoring happens in the PAP. This is where the business rules are translated into access policies.' },
        ],
      },
    ],
    concepts: ['DAC / RBAC / ABAC / PBAC are different models for different needs', 'PAP writes, PIP informs, PDP decides, PEP enforces', 'RBAC scales well; ABAC handles complex context-aware decisions'],
    xpReward: 350,
    achievementUnlock: 'policy_wonk',
  },

  /* ── M04: IAM Architecture ───────────────── */
  {
    id: 4, mission: 'M04', icon: '🏗️', color: '#f59e0b',
    title: 'The Blueprint',
    subtitle: 'IAM Reference Architecture',
    context: 'NEXUS is growing to 2,000 employees across 5 offices. The patchwork of ad-hoc identity tools is breaking. You need to design a proper IAM architecture that can scale.',
    bullets: [
      'The Identity Provider (IdP) is the authority that authenticates users',
      'Identity Repositories store identity data (directories, databases)',
      'Credential Service Providers issue and manage credentials',
      'Audit Repositories log all identity events for compliance and forensics',
    ],
    activities: [
      {
        type: 'sort', id: 'm04-sort1',
        title: 'IAM Architecture Components',
        instruction: 'NEXUS\'s architect drew a component diagram. Sort each component into its correct architectural layer.',
        bins: [
          { id: 'identity_store',  label: 'Identity Store',     icon: '🗄️', desc: 'Stores identity data', color: '#00d4ff' },
          { id: 'auth_service',    label: 'Auth Service',       icon: '🔐', desc: 'Handles authentication', color: '#7c3aed' },
          { id: 'audit',           label: 'Audit & Compliance', icon: '📊', desc: 'Logging and reporting', color: '#f59e0b' },
          { id: 'governance',      label: 'Governance',         icon: '⚖️', desc: 'Access decisions & reviews', color: '#10b981' },
        ],
        items: [
          { text: 'Active Directory / LDAP', bin: 'identity_store', explain: 'A directory service — the canonical store for user identity data, group memberships, and attributes.' },
          { text: 'SAML / OIDC Identity Provider', bin: 'auth_service', explain: 'The IdP handles federated authentication — it asserts who the user is to applications that trust it.' },
          { text: 'SIEM log ingestion for identity events', bin: 'audit', explain: 'Audit logs capture login attempts, access grants/denials, and admin actions — critical for compliance and incident response.' },
          { text: 'IGA platform (SailPoint, Saviynt)', bin: 'governance', explain: 'Identity Governance & Administration platforms manage access reviews, certifications, and role management.' },
          { text: 'Credential vault (password manager, secrets manager)', bin: 'auth_service', explain: 'Credential Service Providers store, issue, and rotate credentials — from passwords to API keys to certificates.' },
          { text: 'Access review and certification reports', bin: 'audit', explain: 'Certifications are governance activities — but the evidence and reports belong in audit repositories for compliance.' },
          { text: 'HR system as authoritative identity source', bin: 'identity_store', explain: 'The HR system is often the Identity Information Authority — the authoritative source of truth about who works at the company.' },
          { text: 'Role mining and entitlement management', bin: 'governance', explain: 'Role management and entitlement analysis are governance functions — they define what access should look like.' },
        ],
      },
      {
        type: 'connect', id: 'm04-con1',
        title: 'Connect the Architecture',
        instruction: 'Match each IAM component on the left to what it does on the right. Click a component, then click its role.',
        pairs: [
          { left: 'Identity Provider (IdP)',       right: 'Asserts user identity to applications and services', leftId: 'idp', rightId: 'ridp' },
          { left: 'Credential Service Provider',   right: 'Issues and manages user credentials (passwords, certs)', leftId: 'csp', rightId: 'rcsp' },
          { left: 'Identity Repository',           right: 'Stores the master record of all user identities', leftId: 'repo', rightId: 'rrepo' },
          { left: 'Audit Repository',              right: 'Records all identity and access events for compliance', leftId: 'audit', rightId: 'raudit' },
          { left: 'Identity Information Authority',right: 'The authoritative source of truth (e.g., HR system)', leftId: 'iia', rightId: 'riia' },
        ],
      },
    ],
    concepts: ['IdP handles authentication; IGA handles governance', 'HR is often the authoritative identity source', 'Every identity event should be logged to an audit repository'],
    xpReward: 300,
    achievementUnlock: null,
  },

  /* ── M05: IGA ────────────────────────────── */
  {
    id: 5, mission: 'M05', icon: '⚖️', color: '#10b981',
    title: 'The Audit',
    subtitle: 'Identity Governance & Administration',
    context: 'NEXUS\'s quarterly audit found 340 users with access they no longer need. Three employees have access combinations that violate Segregation of Duties rules. The auditors are unhappy.',
    bullets: [
      'Governance ensures the RIGHT people have the RIGHT access for the RIGHT reasons',
      'Access certifications are regular reviews where managers approve or revoke access',
      'Segregation of Duties prevents one person from controlling an entire risky process',
      'Identity analytics detects anomalies like access creep and dormant accounts',
    ],
    activities: [
      {
        type: 'sort', id: 'm05-sort1',
        title: 'The Access Certification Queue',
        instruction: 'You\'re reviewing the access certification queue. For each access record, decide: CERTIFY (keep the access — it\'s justified) or REVOKE (remove it — it\'s no longer appropriate). Think like an auditor.',
        bins: [
          { id: 'certify', label: 'CERTIFY', icon: '✅', desc: 'Keep the access — it\'s legitimate', color: '#10b981' },
          { id: 'revoke',  label: 'REVOKE',  icon: '🚫', desc: 'Remove the access — not appropriate', color: '#ef4444' },
        ],
        items: [
          { text: 'Sarah (HR Manager) has read access to all HR records — last used yesterday', bin: 'certify', explain: 'Certify — Sarah\'s job requires HR data access, she uses it regularly, and it\'s appropriate for her role.' },
          { text: 'Tom (Sales Rep) has admin access to the financial system — last used 8 months ago', bin: 'revoke', explain: 'Revoke — Sales reps don\'t need financial admin access. 8 months unused is a red flag. This is "access creep."' },
          { text: 'Dev (Engineer) has read access to the code repository — used daily', bin: 'certify', explain: 'Certify — an engineer actively using the code repository is exactly what that access is for.' },
          { text: 'Maria (left the company 3 months ago) still has an active email account', bin: 'revoke', explain: 'Immediate revoke — orphaned accounts from former employees are a critical security risk. This should have been caught at offboarding.' },
          { text: 'Jake (Finance) can both create payment orders AND approve them', bin: 'revoke', explain: 'Revoke one of these — this is a Segregation of Duties violation! One person controlling both sides of a financial transaction is a major fraud risk.' },
          { text: 'Ana (Legal Counsel) has access to legal document repository — used weekly', bin: 'certify', explain: 'Certify — legal counsel actively using legal documents is appropriate and expected.' },
        ],
      },
      {
        type: 'sort', id: 'm05-sort2',
        title: 'Governance vs Administration',
        instruction: 'IGA has two sides: Governance (oversight, policy, decision-making) and Administration (the operational tasks that carry out those decisions). Sort each activity into the right bucket.',
        bins: [
          { id: 'governance', label: 'Governance',      icon: '🏛️', desc: 'Policy, oversight, review', color: '#7c3aed' },
          { id: 'admin',      label: 'Administration',  icon: '⚙️', desc: 'Operational execution', color: '#00d4ff' },
        ],
        items: [
          { text: 'Defining the policy: "No one person can both create and approve invoices"', bin: 'governance', explain: 'Governance: this is a policy decision defining Segregation of Duties rules. A business decision, not an IT action.' },
          { text: 'Creating a new user account in Active Directory', bin: 'admin', explain: 'Administration: provisioning a user account is an operational task carrying out governance decisions.' },
          { text: 'Conducting quarterly access reviews', bin: 'governance', explain: 'Governance: access certifications are a governance activity ensuring access remains appropriate over time.' },
          { text: 'Assigning the "Manager" role to a newly promoted employee', bin: 'admin', explain: 'Administration: role assignment is an operational provisioning task based on governance-defined role definitions.' },
          { text: 'Identifying that the Finance team has too many conflicting permissions', bin: 'governance', explain: 'Governance: identifying Segregation of Duties conflicts is an oversight and analysis function.' },
          { text: 'Running automated deprovisioning when an employee offboards', bin: 'admin', explain: 'Administration: automated deprovisioning is operational execution of the leaver process defined by governance policy.' },
        ],
      },
    ],
    concepts: ['Access certifications prevent privilege accumulation over time', 'SoD ensures no single person controls an entire risky process', 'Governance sets policy; Administration executes it'],
    xpReward: 320,
    achievementUnlock: null,
  },

  /* ── M06: User Provisioning ──────────────── */
  {
    id: 6, mission: 'M06', icon: '⚙️', color: '#00d4ff',
    title: 'Welcome Aboard',
    subtitle: 'User Provisioning',
    context: 'NEXUS is hiring 200 people over the next 3 months. The current process: IT manually creates each account, emails credentials, and then waits for access requests to arrive by Slack. It takes 4 days per person. You need to automate this.',
    bullets: [
      'Provisioning creates and manages identity records and access throughout the lifecycle',
      'Birthright access is the baseline access every employee gets automatically on day 1',
      'SCIM is a standard protocol for automating user provisioning between systems',
      'JML (Joiner/Mover/Leaver) events should trigger automated provisioning workflows',
    ],
    activities: [
      {
        type: 'flow', id: 'm06-flow1',
        title: 'Build the Joiner Workflow',
        instruction: 'When a new employee joins NEXUS, a series of provisioning steps must happen in the right order. Build the correct automated workflow.',
        correctOrder: [
          'HR creates the employee record in the HR system (system of record)',
          'HR event triggers the IAM provisioning workflow automatically',
          'IAM system creates the identity in the directory (Active Directory / IdP)',
          'Role-based birthright access is assigned based on job title and department',
          'Accounts are created in downstream systems (email, Slack, Jira, etc.) via SCIM',
          'Welcome email sent with instructions to set a new password',
          'Manager notified that employee is ready to start',
        ],
        steps: [
          'Role-based birthright access is assigned based on job title and department',
          'Accounts are created in downstream systems (email, Slack, Jira, etc.) via SCIM',
          'Manager notified that employee is ready to start',
          'HR creates the employee record in the HR system (system of record)',
          'IAM system creates the identity in the directory (Active Directory / IdP)',
          'Welcome email sent with instructions to set a new password',
          'HR event triggers the IAM provisioning workflow automatically',
        ],
        successMessage: 'A proper provisioning workflow starts with the authoritative source (HR), triggers automatically, creates the identity, assigns birthright access by role, pushes to all downstream systems via SCIM, and notifies stakeholders. No manual steps needed!',
      },
      {
        type: 'sort', id: 'm06-sort1',
        title: 'JML Processing Queue',
        instruction: 'The provisioning system\'s event queue is full. Each event is a JML event that needs the right automated action. Sort each event into the correct processing lane.',
        bins: [
          { id: 'create',   label: 'Create & Provision',    icon: '🟢', desc: 'New identity + birthright access', color: '#10b981' },
          { id: 'update',   label: 'Update & Reconcile',    icon: '🔵', desc: 'Modify existing access', color: '#00d4ff' },
          { id: 'revoke',   label: 'Revoke & Deprovision',  icon: '🔴', desc: 'Remove all access immediately', color: '#ef4444' },
        ],
        items: [
          { text: 'New hire: Alex Kim, Software Engineer, starts Monday', bin: 'create', explain: 'Joiner event → Create & Provision. Create identity, assign birthright access for Engineer role, push to all systems.' },
          { text: 'Jordan promoted to Engineering Lead — effective today', bin: 'update', explain: 'Mover event → Update. Add engineering lead permissions, keep base engineer access, notify new systems if needed.' },
          { text: 'Contract employee last day was Friday — today is Monday', bin: 'revoke', explain: 'Leaver event → Immediate Revoke. All access must be removed as of the end of the employment relationship.' },
          { text: 'Dana transferred from US office to UK office', bin: 'update', explain: 'Mover event → Update. Location change may affect regional system access, compliance attributes, and time zone settings.' },
          { text: 'Intern program ended — 12 interns\' contracts finished', bin: 'revoke', explain: 'Leaver event × 12. Bulk deprovision all intern accounts and access immediately.' },
          { text: 'New vendor onboarded for 6-month security audit contract', bin: 'create', explain: 'Joiner event (contractor). Create a limited-access identity with scope appropriate for the audit, with expiry date set.' },
        ],
      },
    ],
    concepts: ['Automated provisioning starts with the authoritative HR source', 'SCIM standardizes provisioning across SaaS applications', 'Birthright access ensures day-1 productivity without manual requests'],
    xpReward: 320,
    achievementUnlock: 'jml_master',
  },

  /* ── M07: Federation & SSO ───────────────── */
  {
    id: 7, mission: 'M07', icon: '🌐', color: '#7c3aed',
    title: 'United We Stand',
    subtitle: 'Federation & Single Sign-On',
    context: 'NEXUS just signed partnership agreements with 3 companies. 800 partner employees need access to NEXUS systems. Creating 800 accounts manually isn\'t an option. You need identity federation.',
    bullets: [
      'Federation lets users authenticate with their home org and access partner systems',
      'SSO means one login gets you into all connected systems without re-authenticating',
      'Bilateral federation: two orgs trust each other. Multilateral: a hub trusts many.',
      'The Identity Provider (IdP) asserts identity; the Service Provider (SP) trusts and consumes it',
    ],
    activities: [
      {
        type: 'sort', id: 'm07-sort1',
        title: 'Federation Concepts',
        instruction: 'Sort each statement into the correct federation concept.',
        bins: [
          { id: 'idp',            label: 'Identity Provider', icon: '🏠', desc: 'Issues identity assertions', color: '#00d4ff' },
          { id: 'sp',             label: 'Service Provider',  icon: '🖥️', desc: 'Trusts and consumes assertions', color: '#7c3aed' },
          { id: 'bilateral',      label: 'Bilateral Fed.',    icon: '↔️', desc: 'One-to-one trust', color: '#f59e0b' },
          { id: 'multilateral',   label: 'Multilateral Fed.', icon: '🌐', desc: 'Hub-and-spoke trust', color: '#10b981' },
        ],
        items: [
          { text: 'NEXUS authenticates its own employees and vouches for them to partners', bin: 'idp', explain: 'NEXUS acts as an Identity Provider — it authenticates its users and issues assertions that partner SPs trust.' },
          { text: 'Salesforce trusts NEXUS\'s authentication and grants access based on the IdP\'s assertion', bin: 'sp', explain: 'Salesforce is the Service Provider — it doesn\'t authenticate users itself, it trusts the IdP\'s assertion.' },
          { text: 'NEXUS and Partner A set up a direct trust agreement just between them', bin: 'bilateral', explain: 'Bilateral federation: one-to-one. NEXUS and Partner A each configure trust for the other. Simple but doesn\'t scale.' },
          { text: 'An industry consortium hub manages trust for 50 member organizations', bin: 'multilateral', explain: 'Multilateral federation: many organizations join a hub. Trust is managed centrally, not in hundreds of bilateral pairs.' },
          { text: 'Google Workspace authenticates NEXUS employees for all Google apps', bin: 'idp', explain: 'Google Workspace acts as the IdP — it\'s the authority for authenticating NEXUS users across its platform.' },
          { text: 'GitHub Enterprise accepts NEXUS\'s SAML assertions to grant code access', bin: 'sp', explain: 'GitHub Enterprise is the SP — it trusts NEXUS\'s IdP assertions rather than managing user authentication itself.' },
        ],
      },
      {
        type: 'flow', id: 'm07-flow1',
        title: 'SAML SSO: Trace the Login',
        instruction: 'A NEXUS partner employee (from Company A) tries to access a NEXUS application using SAML SSO. Arrange the steps in the correct sequence.',
        correctOrder: [
          'Partner employee clicks "Login with Company A SSO" on NEXUS app',
          'NEXUS application (SP) redirects user to Company A\'s IdP',
          'User authenticates with Company A\'s IdP (username + MFA)',
          'Company A\'s IdP creates a signed SAML assertion with user\'s identity and attributes',
          'SAML assertion is sent back to NEXUS application',
          'NEXUS SP validates the assertion signature against the trusted IdP certificate',
          'NEXUS grants access based on the assertion\'s claims — no new account needed',
        ],
        steps: [
          'NEXUS SP validates the assertion signature against the trusted IdP certificate',
          'User authenticates with Company A\'s IdP (username + MFA)',
          'SAML assertion is sent back to NEXUS application',
          'Partner employee clicks "Login with Company A SSO" on NEXUS app',
          'Company A\'s IdP creates a signed SAML assertion with user\'s identity and attributes',
          'NEXUS grants access based on the assertion\'s claims — no new account needed',
          'NEXUS application (SP) redirects user to Company A\'s IdP',
        ],
        successMessage: 'In SAML SSO, the SP redirects to the IdP, the user authenticates at home, the IdP issues a signed assertion, and the SP validates and trusts it. No credentials are shared — only cryptographically signed claims.',
      },
    ],
    concepts: ['Federation eliminates the need to manage partner accounts', 'IdPs issue assertions; SPs consume and trust them', 'SAML is the dominant enterprise federation protocol'],
    xpReward: 340,
    achievementUnlock: 'fed_builder',
  },

  /* ── M08: OAuth 2.0 & OIDC ───────────────── */
  {
    id: 8, mission: 'M08', icon: '🎫', color: '#ef4444',
    title: 'Pass the Keys',
    subtitle: 'OAuth 2.0 & OpenID Connect',
    context: 'NEXUS is building a mobile app that lets employees view their schedules. The app needs calendar access — but you can\'t let the app handle the employee\'s actual password. Enter OAuth 2.0 and OIDC.',
    bullets: [
      'OAuth 2.0 is an AUTHORIZATION framework — it delegates API access without sharing passwords',
      'OpenID Connect (OIDC) adds AUTHENTICATION on top of OAuth — it proves who the user is',
      'Access Tokens grant access to resources; ID Tokens prove who the authenticated user is',
      'OAuth roles: Resource Owner (user), Client (app), Authorization Server, Resource Server',
    ],
    activities: [
      {
        type: 'sort', id: 'm08-sort1',
        title: 'OAuth 2.0 Roles',
        instruction: 'The NEXUS mobile app scenario has 4 key players. Sort each description into the correct OAuth 2.0 role.',
        bins: [
          { id: 'resource_owner', label: 'Resource Owner',       icon: '👤', desc: 'Owns the data', color: '#00d4ff' },
          { id: 'client',         label: 'Client',               icon: '📱', desc: 'The app requesting access', color: '#7c3aed' },
          { id: 'auth_server',    label: 'Authorization Server', icon: '🔐', desc: 'Issues tokens', color: '#f59e0b' },
          { id: 'resource_server',label: 'Resource Server',      icon: '🗄️', desc: 'Holds the protected data', color: '#10b981' },
        ],
        items: [
          { text: 'The NEXUS employee whose calendar data is being accessed', bin: 'resource_owner', explain: 'The Resource Owner owns the data. They grant (or deny) the Client permission to access their resources.' },
          { text: 'The NEXUS mobile scheduling app', bin: 'client', explain: 'The Client is the application requesting access to the resource. It never sees the user\'s password.' },
          { text: 'The NEXUS SSO system that issues access tokens after user consent', bin: 'auth_server', explain: 'The Authorization Server authenticates the user, gets their consent, and issues tokens to the Client.' },
          { text: 'The calendar API that checks the token and returns schedule data', bin: 'resource_server', explain: 'The Resource Server holds the protected data. It validates the access token and returns the requested resource.' },
          { text: 'The system the employee logs into to say "yes, this app can see my calendar"', bin: 'auth_server', explain: 'The Authorization Server is where the user authenticates and grants consent. It\'s the token issuer.' },
          { text: 'The HR database API being accessed on behalf of the user', bin: 'resource_server', explain: 'Any API or service holding protected resources is the Resource Server. It trusts access tokens from the Auth Server.' },
        ],
      },
      {
        type: 'sort', id: 'm08-sort2',
        title: 'OAuth vs OIDC — What\'s the Difference?',
        instruction: 'OAuth 2.0 and OpenID Connect solve different problems. Sort each use case into the right protocol.',
        bins: [
          { id: 'oauth',  label: 'OAuth 2.0',           icon: '🔑', desc: 'Delegated authorization', color: '#f59e0b' },
          { id: 'oidc',   label: 'OpenID Connect',       icon: '🪪', desc: 'Federated authentication', color: '#7c3aed' },
          { id: 'both',   label: 'Both Together',        icon: '🔗', desc: 'Auth + Access', color: '#10b981' },
        ],
        items: [
          { text: '"Allow this app to post to Twitter on my behalf"', bin: 'oauth', explain: 'OAuth 2.0: this is delegated authorization. The app gets permission to act on the user\'s behalf — not to identify them.' },
          { text: '"Log in with Google" — the app needs to know who you are', bin: 'oidc', explain: 'OIDC: this is federated authentication. OIDC adds the ID Token so the app can verify who the user is.' },
          { text: '"The app needs to both know who I am AND access my Google Drive files"', bin: 'both', explain: 'Both: OIDC for authentication (who are you?) + OAuth for authorization (can you access Drive?).' },
          { text: '"Give this app read-only access to my GitHub repositories"', bin: 'oauth', explain: 'OAuth 2.0: scoped API access delegation. The app gets an access token for GitHub — no identity assertion needed.' },
          { text: '"Sign in to NEXUS with your Microsoft account"', bin: 'oidc', explain: 'OIDC: enterprise SSO uses OIDC. The ID Token tells NEXUS who the Microsoft-authenticated user is.' },
          { text: 'Access Token grants API access; ID Token proves user identity', bin: 'both', explain: 'Access Tokens are OAuth. ID Tokens are OIDC. Together they give you both authorization and authentication.' },
        ],
      },
      {
        type: 'flow', id: 'm08-flow1',
        title: 'OAuth 2.0 Authorization Code Flow',
        instruction: 'The NEXUS app wants to access the employee\'s calendar. Arrange the Authorization Code Flow in the correct order.',
        correctOrder: [
          'User opens NEXUS app and clicks "Connect Calendar"',
          'App redirects user to Authorization Server with client_id and requested scopes',
          'User logs in and sees consent screen: "NEXUS App wants to read your calendar"',
          'User clicks Approve — Authorization Server issues a short-lived Authorization Code',
          'App exchanges Authorization Code for an Access Token (server-side, never exposed)',
          'App uses Access Token to call the Calendar API',
          'Calendar API validates the token and returns the schedule data',
        ],
        steps: [
          'App uses Access Token to call the Calendar API',
          'User logs in and sees consent screen: "NEXUS App wants to read your calendar"',
          'App exchanges Authorization Code for an Access Token (server-side, never exposed)',
          'User opens NEXUS app and clicks "Connect Calendar"',
          'Calendar API validates the token and returns the schedule data',
          'App redirects user to Authorization Server with client_id and requested scopes',
          'User clicks Approve — Authorization Server issues a short-lived Authorization Code',
        ],
        successMessage: 'The Authorization Code Flow keeps tokens off the browser. The user authenticates at the Auth Server, gets a code, and the server-side app exchanges it for a token. The user\'s password is never seen by the client app.',
      },
    ],
    concepts: ['OAuth = authorization (what can you access). OIDC = authentication (who are you)', 'Access Tokens grant API access; ID Tokens identify the user', 'The Auth Code Flow keeps sensitive tokens off the browser'],
    xpReward: 380,
    achievementUnlock: 'token_router',
  },

  /* ── M09: CIAM ───────────────────────────── */
  {
    id: 9, mission: 'M09', icon: '🛍️', color: '#10b981',
    title: 'Customer First',
    subtitle: 'Consumer Identity & Access Management',
    context: 'NEXUS is launching a B2C product. Millions of customers will create accounts. This is totally different from managing employees — customers self-register, expect a frictionless experience, and you must comply with GDPR consent rules.',
    bullets: [
      'CIAM prioritizes user experience AND security — friction kills conversions',
      'Credential stuffing uses breached password lists to attack accounts at scale',
      'Progressive profiling collects data gradually rather than upfront',
      'Consent is mandatory — customers must agree to how their data is used',
    ],
    activities: [
      {
        type: 'configure', id: 'm09-cfg1',
        title: 'Design the Customer Registration Flow',
        instruction: 'Configure NEXUS\'s customer registration experience. Too much friction and customers abandon. Too little security and attackers take over accounts.',
        scenarios: [
          { icon: '🛒', name: 'Customer Signing Up for NEXUS Shop', context: 'New customer, mobile device, wants to checkout quickly.', details: 'Goal: minimize abandonment, collect consent, create a secure account.' },
        ],
        toggles: [
          { id: 'social_login',   label: 'Offer "Sign in with Google/Apple"', sub: 'Reduces friction massively',         impact: { conversion: 40, security: 20, friction: -30 } },
          { id: 'email_verify',   label: 'Require email verification',         sub: 'Confirms real email, reduces bots', impact: { conversion: -10, security: 30, friction: 10 } },
          { id: 'consent_gdpr',   label: 'Show GDPR consent checkboxes',       sub: 'Required for EU customers',         impact: { conversion: -5, security: 10, friction: 5 } },
          { id: 'progressive',    label: 'Use progressive profiling',           sub: 'Ask for more data over time',       impact: { conversion: 20, security: 5, friction: -15 } },
          { id: 'phone_verify',   label: 'Require phone number at signup',     sub: 'Stops bots but adds friction',      impact: { conversion: -25, security: 25, friction: 25 } },
        ],
        targetToggles: ['social_login', 'email_verify', 'consent_gdpr', 'progressive'],
        successMessage: 'Great CIAM design balances security with experience. Social login reduces friction, email verification confirms identity, GDPR consent is legally required, and progressive profiling lets you learn about customers over time without overwhelming them at signup.',
      },
      {
        type: 'sort', id: 'm09-sort1',
        title: 'CIAM vs Enterprise IAM',
        instruction: 'Consumer IAM and Workforce IAM are fundamentally different. Sort each characteristic into the correct type.',
        bins: [
          { id: 'ciam',       label: 'Consumer IAM (CIAM)', icon: '🛒', desc: 'Customer-facing identity', color: '#10b981' },
          { id: 'workforce',  label: 'Workforce IAM',       icon: '🏢', desc: 'Employee identity', color: '#00d4ff' },
          { id: 'both',       label: 'Both',                icon: '🔄', desc: 'Applies to both', color: '#7c3aed' },
        ],
        items: [
          { text: 'Self-service registration — users create their own accounts', bin: 'ciam', explain: 'CIAM: customers self-register. In workforce IAM, IT or HR creates accounts centrally.' },
          { text: 'Account lifecycle managed by HR department', bin: 'workforce', explain: 'Workforce IAM: the employee lifecycle is managed by the organization (HR, IT, IAM team) — not self-service.' },
          { text: 'User experience and conversion rate are primary design goals', bin: 'ciam', explain: 'CIAM must optimize for UX — a bad registration flow costs revenue. Workforce IAM prioritizes security and compliance.' },
          { text: 'MFA to protect account access', bin: 'both', explain: 'Both CIAM and workforce IAM use MFA. The methods and implementation differ (customers get SMS; employees get hardware tokens).' },
          { text: 'Credential stuffing attacks are the primary threat', bin: 'ciam', explain: 'CIAM faces credential stuffing at scale because customer accounts are publicly accessible. Enterprise systems are behind VPNs.' },
          { text: 'GDPR consent required before collecting personal data', bin: 'both', explain: 'Both must comply with GDPR if they handle EU personal data — employees are also data subjects under GDPR.' },
          { text: 'Millions of identities, globally distributed', bin: 'ciam', explain: 'Scale is different: CIAM might handle 50M customers worldwide; workforce IAM handles thousands of employees.' },
          { text: 'Account recovery via security questions or email link', bin: 'ciam', explain: 'CIAM: self-service account recovery is essential since customers can\'t call IT helpdesk. Workforce users can call IT.' },
        ],
      },
    ],
    concepts: ['CIAM scales to millions and prioritizes user experience', 'Consent and progressive profiling are CIAM-specific concepts', 'Credential stuffing is the top CIAM threat — rate limiting and MFA are the defenses'],
    xpReward: 320,
    achievementUnlock: null,
  },

  /* ── M10: Privacy & Compliance ───────────── */
  {
    id: 10, mission: 'M10', icon: '🔒', color: '#7c3aed',
    title: 'Handle with Care',
    subtitle: 'Privacy & Compliance',
    context: 'NEXUS received a letter from the EU Data Protection Authority. A GDPR complaint was filed. A customer wants all their data deleted. Your marketing team wants to use customer data for ads. Things are getting complicated.',
    bullets: [
      'GDPR: data must be collected with consent, used only for stated purposes, and protected',
      'Data minimization: only collect what you actually need',
      'Data controllers decide why data is collected; processors handle it on their behalf',
      'The Right to be Forgotten: individuals can request deletion of their personal data',
    ],
    activities: [
      {
        type: 'sort', id: 'm10-sort1',
        title: 'GDPR Principles in Action',
        instruction: 'The NEXUS legal team is reviewing data handling practices. Sort each action as COMPLIANT or VIOLATION under GDPR principles.',
        bins: [
          { id: 'compliant',  label: 'COMPLIANT',  icon: '✅', desc: 'Follows GDPR principles', color: '#10b981' },
          { id: 'violation',  label: 'VIOLATION',  icon: '⚠️', desc: 'Violates GDPR principles', color: '#ef4444' },
        ],
        items: [
          { text: 'Collecting only email and name at signup — nothing else', bin: 'compliant', explain: 'Data minimization: only collecting what\'s necessary for the service is a core GDPR principle.' },
          { text: 'Selling customer purchase history to an ad network without consent', bin: 'violation', explain: 'Violation: sharing data with third parties without explicit consent, and using data for a purpose customers didn\'t agree to.' },
          { text: 'Deleting all data within 30 days when a customer requests account deletion', bin: 'compliant', explain: 'The Right to Erasure (right to be forgotten) — NEXUS is correctly honoring the customer\'s GDPR right.' },
          { text: 'Keeping customer data indefinitely "just in case it\'s useful later"', bin: 'violation', explain: 'Violation: Storage Limitation principle. Data must not be kept longer than necessary for its stated purpose.' },
          { text: 'Using customer emails (signed up for newsletter) to send targeted ads', bin: 'violation', explain: 'Violation: Purpose Limitation. If users signed up for a newsletter, using their data for ads is a different purpose — requires new consent.' },
          { text: 'Showing users exactly what data you hold about them when they request it', bin: 'compliant', explain: 'Data Subject Access Request (DSAR): individuals have the right to know what data you hold. NEXUS is honoring this right.' },
        ],
      },
      {
        type: 'sort', id: 'm10-sort2',
        title: 'Data Controller vs Data Processor',
        instruction: 'GDPR defines two key roles. Sort each entity into the correct role for NEXUS.',
        bins: [
          { id: 'controller', label: 'Data Controller', icon: '🎛️', desc: 'Decides why and how data is processed', color: '#7c3aed' },
          { id: 'processor',  label: 'Data Processor',  icon: '⚙️', desc: 'Processes data on behalf of the controller', color: '#00d4ff' },
        ],
        items: [
          { text: 'NEXUS Corp — decides to collect customer emails for marketing', bin: 'controller', explain: 'NEXUS is the Data Controller: they determine the purpose and means of processing the personal data.' },
          { text: 'Mailchimp — sends marketing emails on behalf of NEXUS', bin: 'processor', explain: 'Mailchimp is a Data Processor: they process personal data (email addresses) on NEXUS\'s behalf and under NEXUS\'s instructions.' },
          { text: 'Google Analytics — tracking user behavior on NEXUS\'s website', bin: 'processor', explain: 'Google Analytics processes behavioral data on behalf of NEXUS. NEXUS decides to use it (controller); Google runs it (processor).' },
          { text: 'NEXUS decides to build a user behavioral profile for personalization', bin: 'controller', explain: 'NEXUS decides the purpose (personalization) and what data to collect — that makes them the controller.' },
          { text: 'AWS — storing NEXUS customer database in the cloud', bin: 'processor', explain: 'AWS processes (stores, transfers) data on NEXUS\'s behalf. AWS doesn\'t decide why that data is collected — NEXUS does.' },
          { text: 'NEXUS HR — collecting employee data for payroll purposes', bin: 'controller', explain: 'NEXUS HR is the controller for employee data — they determine it\'s needed for payroll and how it\'s used.' },
        ],
      },
    ],
    concepts: ['Data minimization: collect only what you need', 'Purpose limitation: use data only for what users consented to', 'Controllers decide; Processors act on instructions'],
    xpReward: 320,
    achievementUnlock: 'privacy_guard',
  },

  /* ── M11: Laws & Regulations ─────────────── */
  {
    id: 11, mission: 'M11', icon: '⚖️', color: '#f59e0b',
    title: 'By the Book',
    subtitle: 'Laws & Regulations',
    context: 'NEXUS\'s legal team just flagged three situations: a potential identity theft liability, a CCPA request from a California customer, and a question about whether NEXUS\'s identity verification meets legal standards for financial transactions.',
    bullets: [
      'Identity theft laws make unauthorized use of another\'s identity a criminal offense',
      'Consumer protection laws require transparency in how identity data is used',
      'Legal trust frameworks define the legal basis for accepting digital identities',
      'Financial regulations (like KYC/AML) require identity verification for transactions',
    ],
    activities: [
      {
        type: 'sort', id: 'm11-sort1',
        title: 'Legal Compliance Check',
        instruction: 'The NEXUS legal team is auditing actions across the organization. Sort each action as legally REQUIRED, PROHIBITED, or a matter of GOOD PRACTICE.',
        bins: [
          { id: 'required',  label: 'Legally Required', icon: '📜', desc: 'The law demands this', color: '#00d4ff' },
          { id: 'prohibited',label: 'Prohibited',        icon: '🚫', desc: 'The law forbids this', color: '#ef4444' },
          { id: 'practice',  label: 'Good Practice',     icon: '✨', desc: 'Recommended, not mandated', color: '#10b981' },
        ],
        items: [
          { text: 'Verifying customer identity for financial transactions over $10,000 (KYC)', bin: 'required', explain: 'Know Your Customer (KYC) is legally required under anti-money laundering laws for significant financial transactions.' },
          { text: 'Using someone else\'s identity to open a credit account without consent', bin: 'prohibited', explain: 'Identity theft — a criminal offense under laws like the Identity Theft Enforcement and Restitution Act.' },
          { text: 'Sending users a breach notification within 72 hours of discovery (GDPR)', bin: 'required', explain: 'GDPR Article 33 mandates reporting breaches to the supervisory authority within 72 hours of becoming aware.' },
          { text: 'Responding to California residents\' CCPA data deletion requests', bin: 'required', explain: 'CCPA gives California residents the right to request deletion of their personal data — businesses must honor it.' },
          { text: 'Maintaining detailed logs of all administrative access to identity systems', bin: 'practice', explain: 'A strong security and audit practice — legally required in some regulated industries, but good practice everywhere.' },
          { text: 'Impersonating a law enforcement officer to access identity records', bin: 'prohibited', explain: 'Prohibited — both impersonation and unauthorized access to identity records are criminal offenses.' },
        ],
      },
    ],
    concepts: ['KYC/AML requires identity verification for regulated financial activities', 'GDPR mandates 72-hour breach notification', 'Identity theft is a criminal offense across most jurisdictions'],
    xpReward: 280,
    achievementUnlock: null,
  },

  /* ── M12: PKI & Cryptography ─────────────── */
  {
    id: 12, mission: 'M12', icon: '🔗', color: '#00d4ff',
    title: 'Trust No One',
    subtitle: 'PKI & Cryptography',
    context: 'An attacker intercepted NEXUS internal API traffic. The root cause: no certificate validation. The fix requires understanding Public Key Infrastructure — how digital trust is established and maintained.',
    bullets: [
      'PKI uses public/private key pairs: public key is shared, private key is secret',
      'A Certificate Authority (CA) signs certificates, vouching for a public key\'s owner',
      'Certificates can be revoked — via CRL (list) or OCSP (real-time check)',
      'HSMs (Hardware Security Modules) protect private keys in tamper-resistant hardware',
    ],
    activities: [
      {
        type: 'connect', id: 'm12-con1',
        title: 'PKI Components',
        instruction: 'Match each PKI component to its role in the trust infrastructure.',
        pairs: [
          { left: 'Root CA',          right: 'The ultimate trust anchor — signs Intermediate CAs', leftId: 'rca', rightId: 'rrca' },
          { left: 'Intermediate CA',  right: 'Issues end-entity certificates on behalf of the Root CA', leftId: 'ica', rightId: 'rica' },
          { left: 'Digital Certificate', right: 'Binds a public key to an identity, signed by a CA', leftId: 'cert', rightId: 'rcert' },
          { left: 'CRL',              right: 'A published list of certificates that have been revoked', leftId: 'crl', rightId: 'rcrl' },
          { left: 'OCSP',             right: 'Real-time protocol to check if a specific certificate is still valid', leftId: 'ocsp', rightId: 'rocsp' },
          { left: 'HSM',              right: 'Tamper-resistant hardware that stores and protects private keys', leftId: 'hsm', rightId: 'rhsm' },
        ],
      },
      {
        type: 'sort', id: 'm12-sort1',
        title: 'Certificate Lifecycle Events',
        instruction: 'The NEXUS certificate manager needs to take action on each event. Sort each into the correct response.',
        bins: [
          { id: 'issue',   label: 'Issue Certificate',  icon: '📄', desc: 'Create and sign a new cert', color: '#10b981' },
          { id: 'renew',   label: 'Renew Certificate',  icon: '🔄', desc: 'Extend before it expires', color: '#00d4ff' },
          { id: 'revoke',  label: 'Revoke Certificate', icon: '🚫', desc: 'Invalidate immediately', color: '#ef4444' },
        ],
        items: [
          { text: 'New NEXUS API server needs a TLS certificate for HTTPS', bin: 'issue', explain: 'New servers need new certificates issued by the CA. The CA verifies identity and signs the certificate.' },
          { text: 'A TLS certificate expires in 14 days', bin: 'renew', explain: 'Certificate renewal before expiry prevents service outages. Modern systems automate this with tools like ACME/Let\'s Encrypt.' },
          { text: 'An employee whose certificate is used for code signing left the company', bin: 'revoke', explain: 'When a certificate holder is no longer authorized, the certificate must be immediately revoked so it can\'t be used.' },
          { text: 'The private key for a certificate was accidentally committed to GitHub', bin: 'revoke', explain: 'Compromised private key = immediate revocation. Anyone who found the key could impersonate the certificate\'s owner.' },
          { text: 'A 2-year-old certificate is still valid but the CA recommends 1-year certs now', bin: 'renew', explain: 'Best practice renewal — shorter-lived certificates reduce the window of exposure if a key is compromised.' },
        ],
      },
    ],
    concepts: ['CAs sign certificates to establish cryptographic trust', 'Revoke immediately when a private key is compromised', 'OCSP is real-time revocation checking; CRL is a downloadable list'],
    xpReward: 350,
    achievementUnlock: 'chain_of_trust',
  },

  /* ── M13: Non-Human Identity ─────────────── */
  {
    id: 13, mission: 'M13', icon: '🤖', color: '#10b981',
    title: 'Rise of the Machines',
    subtitle: 'Non-Human Identity Management',
    context: 'NEXUS has deployed 200 microservices, 50 AI agents, and 1,000+ IoT sensors. Each needs an identity. These "machines" outnumber humans in the identity ecosystem 10-to-1. Most have no lifecycle management at all.',
    bullets: [
      'Service accounts, API keys, and certificates are all forms of non-human identity',
      'Machine identities need the same lifecycle management as human identities',
      'Orphaned service accounts with excess privilege are a top attack vector',
      'AI agents and automated workloads need scoped, auditable identities',
    ],
    activities: [
      {
        type: 'sort', id: 'm13-sort1',
        title: 'What Type of Non-Human Identity?',
        instruction: 'NEXUS\'s infrastructure has many non-human entities. Sort each into the correct identity category.',
        bins: [
          { id: 'service_account', label: 'Service Account',   icon: '⚙️', desc: 'App/service identity', color: '#00d4ff' },
          { id: 'machine_cert',    label: 'Machine Certificate',icon: '📜', desc: 'Cryptographic machine ID', color: '#7c3aed' },
          { id: 'api_key',         label: 'API Key/Secret',     icon: '🔑', desc: 'Static credential for API access', color: '#f59e0b' },
          { id: 'workload',        label: 'Workload Identity',  icon: '☁️', desc: 'Cloud-native workload ID', color: '#10b981' },
        ],
        items: [
          { text: 'NEXUS-payroll-service account in Active Directory', bin: 'service_account', explain: 'A service account is a non-human account created for an application or service to run as, with specific permissions.' },
          { text: 'TLS client certificate used by microservice A to authenticate to microservice B', bin: 'machine_cert', explain: 'Machine certificates enable mutual TLS (mTLS) — both services prove their identity cryptographically.' },
          { text: 'AWS IAM Role for the EC2 instance running the NEXUS API', bin: 'workload', explain: 'Workload identity in AWS: EC2 instances use IAM roles with temporary credentials — no long-lived secrets needed.' },
          { text: 'Static API key embedded in the mobile app to call the weather API', bin: 'api_key', explain: 'An API key is a static credential. The risk: it doesn\'t expire, can\'t be rotated easily, and if exposed, gives permanent access.' },
          { text: 'Kubernetes service account for the deployment pipeline', bin: 'workload', explain: 'Kubernetes service accounts are workload identities — they identify pods and control what Kubernetes resources they can access.' },
          { text: 'X.509 certificate used by an IoT sensor to authenticate to the NEXUS gateway', bin: 'machine_cert', explain: 'IoT devices use certificates for strong cryptographic authentication — much more secure than shared passwords or API keys.' },
        ],
      },
      {
        type: 'sort', id: 'm13-sort2',
        title: 'Non-Human Identity Risks',
        instruction: 'The NEXUS security team found these non-human identity issues. Sort each by risk level.',
        bins: [
          { id: 'critical', label: 'Critical — Fix Now',  icon: '🔴', desc: 'Immediate security risk', color: '#ef4444' },
          { id: 'high',     label: 'High — Fix Soon',    icon: '🟠', desc: 'Significant risk', color: '#f59e0b' },
          { id: 'medium',   label: 'Medium — Plan It',   icon: '🟡', desc: 'Moderate concern', color: '#eab308' },
        ],
        items: [
          { text: 'A service account has admin rights to the entire production database — and the app only reads one table', bin: 'critical', explain: 'Critical: massive over-privilege. If this service account is compromised, attackers get full database admin access. Apply least privilege immediately.' },
          { text: 'An API key from a terminated contractor is still active', bin: 'critical', explain: 'Critical: orphaned credential from a leaver. This must be revoked immediately — the contractor could still use it.' },
          { text: 'Service account passwords haven\'t been rotated in 3 years', bin: 'high', explain: 'High: long-lived static credentials are a significant risk. If ever compromised, attackers have had 3 years of undetected access.' },
          { text: 'Machine certificates are being managed manually in a spreadsheet', bin: 'high', explain: 'High: manual certificate management leads to missed renewals (outages) and missed revocations (security gaps).' },
          { text: 'Some microservices are using the same shared service account', bin: 'medium', explain: 'Medium: shared accounts make it impossible to audit which service did what, and a compromise affects all services using that account.' },
        ],
      },
    ],
    concepts: ['Machine identities vastly outnumber human identities in modern infrastructure', 'Orphaned accounts and over-privileged service accounts are top attack vectors', 'Apply the same JML lifecycle management to non-human identities as to humans'],
    xpReward: 340,
    achievementUnlock: 'machine_whisperer',
  },

  /* ── M14: Workforce IAM ───────────────────── */
  {
    id: 14, mission: 'M14', icon: '👥', color: '#7c3aed',
    title: 'Build the Team',
    subtitle: 'Workforce IAM',
    context: 'NEXUS is scaling its IAM program. The CISO wants a proper IAM team structure, clear roles, and a roadmap to maturity. Currently one person does everything. That\'s not sustainable.',
    bullets: [
      'IAM programs need clear organizational structure: strategy, operations, engineering, governance',
      'IAM professionals need both technical skills (protocols, tools) and business skills (risk, policy)',
      'IAM maturity models help organizations benchmark and improve their programs over time',
      'Executive sponsorship is critical — IAM decisions affect everyone in the organization',
    ],
    activities: [
      {
        type: 'sort', id: 'm14-sort1',
        title: 'Build the IAM Org Chart',
        instruction: 'NEXUS is hiring for its IAM team. Sort each role into the correct part of the IAM organization.',
        bins: [
          { id: 'strategy',    label: 'Strategy & Architecture', icon: '🗺️', desc: 'Vision, design, standards', color: '#7c3aed' },
          { id: 'operations',  label: 'Operations',             icon: '⚙️', desc: 'Day-to-day execution', color: '#00d4ff' },
          { id: 'governance',  label: 'Governance & Compliance',icon: '⚖️', desc: 'Policy, audit, risk', color: '#f59e0b' },
          { id: 'engineering', label: 'Engineering',            icon: '🔨', desc: 'Build and integrate', color: '#10b981' },
        ],
        items: [
          { text: 'IAM Architect — designs the future-state identity platform', bin: 'strategy', explain: 'The IAM Architect owns the technical vision and standards. They design the target architecture, not day-to-day operations.' },
          { text: 'Access Review Coordinator — runs quarterly certification campaigns', bin: 'governance', explain: 'Governance role: access certifications are a compliance and governance activity, not an engineering task.' },
          { text: 'Helpdesk Specialist — resets passwords and unlocks accounts', bin: 'operations', explain: 'Operations: routine, daily identity tasks like account unlocks and password resets are operational work.' },
          { text: 'IAM Developer — integrates apps with the SSO platform', bin: 'engineering', explain: 'Engineering: building connectors, integrations, and automating identity processes is software engineering work.' },
          { text: 'IAM Policy Manager — writes and maintains access control policies', bin: 'governance', explain: 'Governance: policy authoring is a governance function — defining the rules that the technical systems enforce.' },
          { text: 'IGA Specialist — manages role definitions and provisioning workflows', bin: 'operations', explain: 'IGA operations: managing roles, running provisioning workflows, and handling access requests is daily operations work.' },
        ],
      },
    ],
    concepts: ['IAM teams need strategy, operations, engineering, and governance disciplines', 'IAM is both a technical and business function', 'Maturity models guide organizations from ad-hoc to optimized IAM programs'],
    xpReward: 280,
    achievementUnlock: null,
  },

  /* ── M15: Least Privilege ─────────────────── */
  {
    id: 15, mission: 'M15', icon: '✂️', color: '#ef4444',
    title: 'Less Is More',
    subtitle: 'Least Privilege & Modern Authorization',
    context: 'NEXUS\'s cloud costs doubled after a breach. An engineer\'s overprivileged AWS account was used to spin up 200 crypto-mining instances. The principle of least privilege was ignored. Time to fix it.',
    bullets: [
      'Least privilege: give users ONLY the minimum access needed for their job — nothing more',
      'Just-in-time (JIT) access: grant elevated access only when needed, expire it automatically',
      'CIEM (Cloud Infrastructure Entitlement Management) finds over-privileged cloud identities',
      'Privilege creep: access accumulates over time as roles change but old access is never removed',
    ],
    activities: [
      {
        type: 'sort', id: 'm15-sort1',
        title: 'The Permission Audit',
        instruction: 'You\'re auditing a developer\'s access. Their role: "software engineer working on the frontend billing module." For each permission, decide if it follows least privilege.',
        bins: [
          { id: 'keep',   label: 'Keep — Job Requires It', icon: '✅', desc: 'Minimum necessary access', color: '#10b981' },
          { id: 'remove', label: 'Remove — Violates Least Priv', icon: '✂️', desc: 'More than needed', color: '#ef4444' },
        ],
        items: [
          { text: 'Read access to billing module code repository', bin: 'keep', explain: 'Keep — a frontend billing developer absolutely needs to read the billing code they\'re working on.' },
          { text: 'Admin access to the production HR database', bin: 'remove', explain: 'Remove — a frontend billing developer has no legitimate reason to have admin access to HR data. Major over-privilege.' },
          { text: 'Write access to the billing module repository', bin: 'keep', explain: 'Keep — developers need to commit code. Write access to their own module\'s repo is the minimum necessary.' },
          { text: 'Full S3 bucket write access to ALL company storage', bin: 'remove', explain: 'Remove — they should have access only to the specific S3 buckets their work requires, not all company storage.' },
          { text: 'Deploy access to staging environment for billing service', bin: 'keep', explain: 'Keep — staging deploy access is necessary to test changes before production. Scoped to their service.' },
          { text: 'Root access to all production EC2 instances', bin: 'remove', explain: 'Remove — no developer needs root access to all production servers. This is the definition of over-privilege.' },
          { text: 'Read access to billing service logs in CloudWatch', bin: 'keep', explain: 'Keep — developers need to read logs to debug their own service. Scoped to billing logs is appropriate.' },
          { text: 'Access to delete production database records', bin: 'remove', explain: 'Remove — delete permissions on production databases should require special approval and be JIT, not standing access.' },
        ],
      },
      {
        type: 'sort', id: 'm15-sort2',
        title: 'Standing Access vs Just-in-Time',
        instruction: 'NEXUS is modernizing its access model. Sort each access scenario into whether it should be Standing Access (always available) or Just-in-Time Access (granted on-demand, time-limited).',
        bins: [
          { id: 'standing', label: 'Standing Access', icon: '🏛️', desc: 'Always available, ongoing need', color: '#00d4ff' },
          { id: 'jit',      label: 'Just-in-Time',    icon: '⏱️', desc: 'On-demand, auto-expires', color: '#7c3aed' },
        ],
        items: [
          { text: 'Developer needs read access to their team\'s code repo every day', bin: 'standing', explain: 'Standing access is appropriate when access is needed continuously for day-to-day work.' },
          { text: 'SRE needs production database admin access to investigate an incident', bin: 'jit', explain: 'JIT: emergency production access should be granted for the duration of the incident, then automatically revoked.' },
          { text: 'Security engineer needs access to all logs for a 2-hour forensic investigation', bin: 'jit', explain: 'JIT: scoped, time-limited access for a specific task. Grant for 2 hours, automatically expire.' },
          { text: 'HR manager needs daily read access to employee records in the HR system', bin: 'standing', explain: 'Standing access for routine, ongoing job requirements. HR managers need this every day to do their job.' },
          { text: 'Developer needs production deploy access for an approved release window', bin: 'jit', explain: 'JIT: production deployments should be approved and time-bounded, not perpetual standing access.' },
        ],
      },
    ],
    concepts: ['Least privilege prevents blast radius when credentials are compromised', 'JIT access eliminates standing privilege — reducing standing attack surface', 'CIEM specifically addresses the explosion of cloud entitlements'],
    xpReward: 360,
    achievementUnlock: 'least_priv',
  },

  /* ── M16: Decentralized Identity ─────────── */
  {
    id: 16, mission: 'M16', icon: '🌟', color: '#7c3aed',
    title: 'The Future',
    subtitle: 'Decentralized Identity',
    context: 'NEXUS wants to eliminate passwords entirely and let users own their identity data. A new technology — Decentralized Identifiers (DIDs) and Verifiable Credentials — makes this possible without a central identity provider.',
    bullets: [
      'DIDs are unique identifiers controlled by the user, not a central authority',
      'Verifiable Credentials are tamper-evident digital credentials that can be presented anywhere',
      'The trust triangle: Issuers create credentials, Holders store them, Verifiers check them',
      'Digital wallets store credentials — like a real wallet, but cryptographically secure',
    ],
    activities: [
      {
        type: 'connect', id: 'm16-con1',
        title: 'The Decentralized Identity Trust Triangle',
        instruction: 'Map each role in decentralized identity to its responsibility.',
        pairs: [
          { left: 'Issuer',                right: 'Creates and signs verifiable credentials (e.g., university, DMV, employer)', leftId: 'issuer', rightId: 'rissuer' },
          { left: 'Holder',                right: 'Receives credentials and stores them in their digital wallet', leftId: 'holder', rightId: 'rholder' },
          { left: 'Verifier',              right: 'Receives and cryptographically verifies credential authenticity', leftId: 'verifier', rightId: 'rverifier' },
          { left: 'DID (Decentralized Identifier)', right: 'A globally unique, user-controlled identifier anchored to a decentralized system', leftId: 'did', rightId: 'rdid' },
          { left: 'Digital Wallet',        right: 'The user\'s app that stores, manages, and presents verifiable credentials', leftId: 'wallet', rightId: 'rwallet' },
          { left: 'Verifiable Credential', right: 'A tamper-evident digital credential cryptographically signed by the issuer', leftId: 'vc', rightId: 'rvc' },
        ],
      },
      {
        type: 'flow', id: 'm16-flow1',
        title: 'Verifiable Credential Exchange',
        instruction: 'Alex wants to prove their employment at NEXUS to open a bank account — without NEXUS being in the loop. Arrange the decentralized identity flow.',
        correctOrder: [
          'NEXUS (Issuer) creates a Verifiable Credential: "Alex Chen is employed at NEXUS"',
          'NEXUS signs the credential with NEXUS\'s private key and sends it to Alex',
          'Alex stores the credential in their digital wallet',
          'Alex applies for a bank account and the bank (Verifier) requests proof of employment',
          'Alex\'s wallet presents the NEXUS employment credential to the bank',
          'Bank resolves NEXUS\'s DID to get NEXUS\'s public key (no call to NEXUS needed)',
          'Bank verifies the credential signature — confirmed authentic without contacting NEXUS',
          'Alex gets the bank account — NEXUS was never involved in the verification',
        ],
        steps: [
          'Alex\'s wallet presents the NEXUS employment credential to the bank',
          'NEXUS signs the credential with NEXUS\'s private key and sends it to Alex',
          'Bank resolves NEXUS\'s DID to get NEXUS\'s public key (no call to NEXUS needed)',
          'Alex applies for a bank account and the bank (Verifier) requests proof of employment',
          'NEXUS (Issuer) creates a Verifiable Credential: "Alex Chen is employed at NEXUS"',
          'Alex gets the bank account — NEXUS was never involved in the verification',
          'Alex stores the credential in their digital wallet',
          'Bank verifies the credential signature — confirmed authentic without contacting NEXUS',
        ],
        successMessage: 'This is the power of decentralized identity: NEXUS issues a credential once, Alex controls it in their wallet, and any verifier can confirm it cryptographically — without calling NEXUS. Privacy-preserving, user-controlled, and tamper-evident.',
      },
    ],
    concepts: ['DIDs give users control of their own identifiers — no central authority needed', 'Verifiable credentials are cryptographically signed — unforgeable and instantly verifiable', 'The trust triangle (Issuer → Holder → Verifier) works without a central broker'],
    xpReward: 380,
    achievementUnlock: 'future_id',
  },

]; // end MODULES
